### ISSUE TITLE
Pytorch RTDETR

### ISSUE THREAD

**Issue by lyuwenyu** [lyuwenyu/RT-DETR#42]
## code

https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_pytorch

## weight 

The performance details see model zoo [table](https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_paddle).

[rtdetr_r18vd_5x_coco_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r18vd_5x_coco_objects365_from_paddle.pth)
[rtdetr_r18vd_1x_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r18vd_1x_objects365_from_paddle.pth)

[rtdetr_r50vd_6x_coco_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_6x_coco_from_paddle.pth)
[rtdetr_r50vd_2x_coco_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_2x_coco_objects365_from_paddle.pth)
[rtdetr_r50vd_1x_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r50vd_1x_objects365_from_paddle.pth)

[rtdetr_r101vd_6x_coco_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r101vd_6x_coco_from_paddle.pth)
[rtdetr_r101vd_2x_coco_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r101vd_2x_coco_objects365_from_paddle.pth)
[rtdetr_r101vd_1x_objects365_from_paddle.pth](https://github.com/lyuwenyu/storage/releases/download/v0.1/rtdetr_r101vd_1x_objects365_from_paddle.pth)

**Comment by Zhao-Yian** [comment]
Thanks for your tireless efforts on our behalf！

**Comment by flyingbird9** [comment]
May I ask if rt detr has used dynamic anchor box updates for dab-detr？

**Comment by lyuwenyu** [comment]
## TODO
- [x] Training
- [x] Evaluation
- [x] Export onnx
- [x] Upload source code
- [x] Upload weight convert from paddle, see [links](https://github.com/lyuwenyu/RT-DETR/issues/42)
- [ ] Align training with the [paddle version](../rtdetr_paddle/)


## Quick start

<details open>
<summary>Install</summary>

```bash
pip install -r requirements.txt
```

</details>


<details>
<summary>Data</summary>

- Download and extract COCO 2017 train and val images.
```
path/to/coco/
  annotations/  # annotation json files
  train2017/    # train images
  val2017/      # val images
```
- Modify config [`img_folder`, `ann_file`](configs/dataset/coco_detection.yml)
</details>



<details>
<summary>Training & Evaluation</summary>

- Training on a Single GPU:

```shell
# training on single-gpu
export CUDA_VISIBLE_DEVICES=0
python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
```

- Training on Multiple GPUs:

```shell
# train on multi-gpu
export CUDA_VISIBLE_DEVICES=0,1,2,3
torchrun --nproc_per_node=4 tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml
```

- Evaluation on Multiple GPUs:

```shell
# val on multi-gpu
export CUDA_VISIBLE_DEVICES=0,1,2,3
torchrun --nproc_per_node=4 tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml -r path/to/checkpoint --test-only
```

</details>



<details>
<summary>Export</summary>

```shell
python tools/export_onnx.py -c configs/rtdetr/rtdetr_r18vd_6x_coco.yml -r path/to/checkpoint --check
```
</details>




<details>
<summary>Finetune</summary>

Set `remap_mscoco_category: False`. This var only works for ms-coco dataset.

</details>

**Comment by hiyyg** [comment]
The pytorch evaluation seems strange. I tested with
```
python3 tools/train.py --config configs/rtdetr/rtdetr_r18vd_6x_coco.yml --load-from rtdetr_weights/rtdetr_r18vd_5x_coco_objects365_from_paddle.pth --test-only
```
The results:
```
Averaged stats:
Accumulating evaluation results...
DONE (t=11.52s).
IoU metric: bbox
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.541
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.705
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.587
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.333
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.559
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.700
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.375
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.659
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 1.028
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.555
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 1.175
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 2.366
```
- The AP does not match https://github.com/lyuwenyu/RT-DETR/tree/main/rtdetr_paddle
- Some of the AR values are larger than 1

What was wrong here?

**Comment by rafaelpadilla** [comment]
Thanks for RT-DETR :) 

It would be so valuable if the links for the weights were in the README.md.

**Comment by ramonhollands** [comment]
Thanks for this amazing repo!
Are there also configs/weights available for the scaled R18 used in the paper? 
Thanks in advance!
Regards, Ramon
